version: 2
updates:
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    time: "06:00"
    timezone: "America/Toronto"
  commit-message:
    prefix: "build: "

# Maintain pyproject.toml dependencies
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
    time: "06:00"
    timezone: "America/Toronto"
  commit-message:
    prefix: "build: "
